import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

const stageLabels = {
  new_lead: 'New Lead', contacted: 'Contacted', meeting_scheduled: 'Meeting Scheduled',
  in_discussion: 'In Discussion', collaborating: 'Collaborating', partnered: 'Partnered', archived: 'Archived',
};

function addFooter(doc) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by URME · ${format(new Date(), 'MMM d, yyyy')}`, 20, doc.internal.pageSize.height - 10);
  }
}

export function exportBusinessPDF(business, interactions = [], matches = []) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text('URME', margin, y);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('Business Profile Report', pageWidth / 2 - 20, y);
  doc.text(format(new Date(), 'MMM d, yyyy'), pageWidth - 50, y);
  doc.setDrawColor(200);
  doc.line(margin, y + 3, pageWidth - margin, y + 3);
  y += 12;

  // Section 1 - Overview
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text(business.name || 'Unknown', margin, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  doc.text(`Industry: ${business.industry || 'N/A'}`, margin, y); y += 5;
  doc.text(`Stage: ${stageLabels[business.stage] || business.stage || 'N/A'}`, margin, y); y += 5;
  doc.text(`Location: ${[business.city, business.state].filter(Boolean).join(', ') || 'N/A'}`, margin, y); y += 5;
  doc.text(`Health Score: ${business.health_score ?? 'N/A'}/100`, margin, y); y += 10;

  // Section 2 - Contact Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Contact Information', margin, y); y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  doc.text(`Contact: ${business.contact_name || 'N/A'}`, margin, y); y += 5;
  doc.text(`Title: ${business.contact_title || 'N/A'}`, margin, y); y += 5;
  doc.text(`Email: ${business.contact_email || 'N/A'}`, margin, y); y += 5;
  doc.text(`Phone: ${business.contact_phone || 'N/A'}`, margin, y); y += 5;
  doc.text(`LinkedIn: ${business.linkedin || 'N/A'}`, margin, y); y += 5;
  doc.text(`Website: ${business.website || 'N/A'}`, margin, y); y += 10;

  // Section 3 - About
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('About', margin, y); y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  const descLines = doc.splitTextToSize(`Description: ${business.description || 'N/A'}`, pageWidth - margin * 2);
  doc.text(descLines, margin, y); y += descLines.length * 5 + 2;
  const needsLines = doc.splitTextToSize(`Needs: ${business.needs || 'N/A'}`, pageWidth - margin * 2);
  doc.text(needsLines, margin, y); y += needsLines.length * 5 + 2;
  const offersLines = doc.splitTextToSize(`Offers: ${business.offers || 'N/A'}`, pageWidth - margin * 2);
  doc.text(offersLines, margin, y); y += offersLines.length * 5 + 6;

  // Section 4 - Recent Activity
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Recent Activity (Last 10)', margin, y); y += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  if (interactions.length === 0) {
    doc.text('No interactions logged', margin, y); y += 5;
  } else {
    interactions.slice(0, 10).forEach(int => {
      if (y > doc.internal.pageSize.height - 25) { doc.addPage(); y = 20; }
      const dateStr = int.interaction_date ? format(new Date(int.interaction_date), 'MMM d, yyyy') : '';
      const notes = (int.notes || '').slice(0, 50);
      doc.text(`${dateStr} | ${int.type} | ${int.title || ''}`, margin, y); y += 4;
      if (notes) { doc.text(`  ${notes}`, margin, y); y += 4; }
      y += 1;
    });
  }
  y += 6;

  // Section 5 - Matches
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Matches', margin, y); y += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  if (matches.length === 0) {
    doc.text('No matches found', margin, y);
  } else {
    matches.forEach(m => {
      if (y > doc.internal.pageSize.height - 20) { doc.addPage(); y = 20; }
      const partner = m.business_a_name === business.name ? m.business_b_name : m.business_a_name;
      doc.text(`${partner} — Score: ${m.synergy_score || 'N/A'} — Status: ${m.status}`, margin, y); y += 4;
    });
  }

  addFooter(doc);
  doc.save(`${(business.name || 'business').replace(/\s+/g, '_')}_profile.pdf`);
}

export function exportPipelineReportPDF(businesses) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  let y = 20;

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text(`URME Pipeline Report`, margin, y); y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(format(new Date(), 'MMMM d, yyyy'), margin, y); y += 8;

  // Summary
  const active = businesses.filter(b => b.stage !== 'archived');
  const avgHealth = active.length > 0 ? Math.round(active.reduce((s, b) => s + (b.health_score || 0), 0) / active.length) : 0;
  const stageCounts = {};
  active.forEach(b => { stageCounts[b.stage] = (stageCounts[b.stage] || 0) + 1; });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text(`Total Active Businesses: ${active.length}`, margin, y); y += 5;
  doc.text(`Average Health Score: ${avgHealth}/100`, margin, y); y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  Object.entries(stageLabels).filter(([k]) => k !== 'archived').forEach(([stage, label]) => {
    doc.text(`${label}: ${stageCounts[stage] || 0}`, margin, y); y += 4;
  });
  y += 5;

  // Table
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.setFontSize(9);
  doc.text('Name', margin, y); doc.text('Stage', 90, y); doc.text('Health', 130, y); doc.text('Last Contact', 155, y);
  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60);
  doc.setFontSize(8);
  const sorted = [...active].sort((a, b) => {
    const stageOrder = ['new_lead', 'contacted', 'meeting_scheduled', 'in_discussion', 'collaborating', 'partnered'];
    const sa = stageOrder.indexOf(a.stage), sb = stageOrder.indexOf(b.stage);
    if (sa !== sb) return sa - sb;
    return (b.health_score || 0) - (a.health_score || 0);
  });
  sorted.forEach(b => {
    if (y > doc.internal.pageSize.height - 20) { doc.addPage(); y = 20; }
    doc.text((b.name || '').slice(0, 35), margin, y);
    doc.text(stageLabels[b.stage] || b.stage || '', 90, y);
    doc.text(`${b.health_score ?? 0}`, 130, y);
    doc.text(b.last_interaction_date ? format(new Date(b.last_interaction_date), 'MMM d, yy') : 'Never', 155, y);
    y += 5;
  });

  addFooter(doc);
  doc.save('URME_pipeline_report.pdf');
}

export function exportFinanceReportPDF(entries, dateRange) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  let y = 20;

  const revenue = entries.filter(e => e.type === 'revenue').reduce((s, e) => s + (e.amount || 0), 0);
  const expenses = entries.filter(e => e.type === 'expense').reduce((s, e) => s + (e.amount || 0), 0);
  const net = revenue - expenses;

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('URME Financial Summary', margin, y); y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(format(new Date(), 'MMMM d, yyyy'), margin, y); y += 8;

  // Totals
  doc.setFontSize(11);
  doc.text(`Total Revenue: $${revenue.toLocaleString()}`, margin, y); y += 6;
  doc.text(`Total Expenses: $${expenses.toLocaleString()}`, margin, y); y += 6;
  doc.text(`Net: $${net.toLocaleString()}`, margin, y); y += 8;

  // Table
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Date', margin, y); doc.text('Category', 50, y); doc.text('Description', 95, y); doc.text('Amount', 150, y); doc.text('Status', 175, y);
  y += 4;
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60);
  doc.setFontSize(8);
  entries.forEach(e => {
    if (y > doc.internal.pageSize.height - 20) { doc.addPage(); y = 20; }
    doc.text(e.date ? format(new Date(e.date), 'MMM d, yy') : '', margin, y);
    doc.text((e.category || '').replace(/_/g, ' ').slice(0, 20), 50, y);
    doc.text((e.description || '').slice(0, 25), 95, y);
    doc.text(`$${(e.amount || 0).toLocaleString()}`, 150, y);
    doc.text(e.payment_status || '', 175, y);
    y += 5;
  });

  addFooter(doc);
  doc.save('URME_financial_summary.pdf');
}