-- Schema reconciliation: every column the app writes, for every table in the
-- base44Client TABLE_MAP.
--
-- Context: the live database was rebuilt by hand from a reconstructed schema and
-- some columns were lost in the process, so inserts fail with PGRST204
-- ("Could not find the '<col>' column of '<table>' in the schema cache").
-- The confirmed case was businesses.address / businesses.assigned_to_name.
--
-- This migration was generated by sweeping every base44.entities.*.create() and
-- .update() call site in src/, plus the default form-state object of every form
-- and create dialog, and cross-checking against the reference entity schemas in
-- base44/entities/*.jsonc.
--
-- Additive and idempotent only: ADD COLUMN IF NOT EXISTS. No drops, no renames,
-- no type changes, no constraint changes. Columns that already exist are left
-- exactly as they are, including their current type -- so for an existing column
-- the type named below is documentation of intent, not an assertion about the
-- live schema.
--
-- Items that need a human decision (CHECK-constraint conflicts, empty-string
-- writes into uuid/timestamptz columns, and the created_date/updated_date read
-- contract) are listed at the bottom of this file. They are NOT applied here.

begin;

-- ── businesses (Business) ────────────────────────────────────────────────────
-- Writers: components/business/BusinessForm.jsx (create + edit), pages/Businesses.jsx,
-- pages/BusinessDetail.jsx, pages/Pipeline.jsx, components/import/CSVImportDialog.jsx,
-- components/shared/QuickCapture.jsx, components/business/BulkLogInteractionModal.jsx
alter table if exists public.businesses
  add column if not exists name text,
  add column if not exists industry text,
  add column if not exists description text,
  add column if not exists needs text,
  add column if not exists offers text,
  add column if not exists contact_name text,
  add column if not exists contact_title text,
  add column if not exists contact_email text,
  add column if not exists contact_phone text,
  add column if not exists linkedin text,
  add column if not exists website text,
  add column if not exists address text,
  add column if not exists stage text,
  add column if not exists assigned_to uuid,
  add column if not exists assigned_to_name text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists tags text[],
  add column if not exists notes text,
  add column if not exists health_score integer,
  add column if not exists interaction_count integer,
  add column if not exists last_interaction_date timestamptz,
  add column if not exists next_follow_up timestamptz,
  add column if not exists latitude numeric,
  add column if not exists longitude numeric;

-- ── contacts (Contact) ───────────────────────────────────────────────────────
-- Writers: components/business/ContactsCard.jsx, components/business/LogInteractionForm.jsx
-- (inline "Add new contact"), pages/Contacts.jsx, pages/ContactProfile.jsx
alter table if exists public.contacts
  add column if not exists business_id uuid,
  add column if not exists business_name text,
  add column if not exists full_name text,
  add column if not exists title text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists linkedin text,
  add column if not exists notes text;

-- ── interactions (Interaction) ───────────────────────────────────────────────
-- Writers: components/business/LogInteractionForm.jsx via pages/BusinessDetail.jsx,
-- components/business/BulkLogInteractionModal.jsx, utils/automations.js
alter table if exists public.interactions
  add column if not exists business_id uuid,
  add column if not exists business_name text,
  add column if not exists contact_id uuid,
  add column if not exists contact_name text,
  add column if not exists type text,
  add column if not exists title text,
  add column if not exists notes text,
  add column if not exists outcome text,
  add column if not exists interaction_date timestamptz,
  add column if not exists team_member text,
  add column if not exists logged_by_id uuid,
  add column if not exists logged_by_name text,
  add column if not exists attachment_url text,
  add column if not exists attachment_name text;

-- ── matches (Match) ──────────────────────────────────────────────────────────
-- Writers: pages/Businesses.jsx (Synergy Scanner), components/business/MatchList.jsx
alter table if exists public.matches
  add column if not exists business_a_id uuid,
  add column if not exists business_a_name text,
  add column if not exists business_b_id uuid,
  add column if not exists business_b_name text,
  add column if not exists synergy_score numeric,
  add column if not exists reason text,
  add column if not exists status text;

-- ── events (Event) ───────────────────────────────────────────────────────────
-- Writers: pages/Events.jsx (EventForm create + edit),
-- components/business/EventEngagements.jsx ("Link Event")
-- Note: "time" is a free-text field ("6:00 PM" from a plain text input), not a
-- time/timestamp value -- see pages/Events.jsx. Keep it text.
alter table if exists public.events
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists "date" timestamptz,
  add column if not exists "time" text,
  add column if not exists location text,
  add column if not exists status text,
  add column if not exists event_type text,
  add column if not exists objectives text,
  add column if not exists target_industries text[],
  add column if not exists post_event_notes text,
  add column if not exists organizer_name text,
  add column if not exists attendee_business_ids text[],
  add column if not exists attendee_count integer;

-- ── tasks (Task) ─────────────────────────────────────────────────────────────
-- Writers: pages/Tasks.jsx, components/shared/QuickCapture.jsx, utils/automations.js
alter table if exists public.tasks
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists status text,
  add column if not exists priority text,
  add column if not exists due_date timestamptz,
  add column if not exists assigned_to uuid,
  add column if not exists assigned_to_name text,
  add column if not exists business_id uuid,
  add column if not exists business_name text;

-- ── ideas (Idea) ─────────────────────────────────────────────────────────────
-- Writers: pages/Ideas.jsx (create, edit, vote, comment, AI improve),
-- components/shared/QuickCapture.jsx
alter table if exists public.ideas
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists category text,
  add column if not exists status text,
  add column if not exists votes integer,
  add column if not exists voted_by text[],
  add column if not exists comments jsonb,
  add column if not exists author_name text;

-- ── discussions (Discussion) ─────────────────────────────────────────────────
-- Writers: components/sync/NewThreadDialog.jsx via pages/SyncHub.jsx (create,
-- reply, pin, archive)
-- linked_business_name / linked_event_name are absent from
-- base44/entities/Discussion.jsonc but the dialog writes them and both
-- components/sync/ThreadView.jsx and ThreadCard.jsx read them back, matching the
-- id+name denormalisation that finance_entries already uses.
alter table if exists public.discussions
  add column if not exists title text,
  add column if not exists content text,
  add column if not exists category text,
  add column if not exists author_name text,
  add column if not exists linked_business_id uuid,
  add column if not exists linked_business_name text,
  add column if not exists linked_event_id uuid,
  add column if not exists linked_event_name text,
  add column if not exists replies jsonb,
  add column if not exists pinned boolean;

-- ── finance_entries (FinanceEntry) ───────────────────────────────────────────
-- Writers: components/finance/FinanceEntryForm.jsx via pages/Finance.jsx
-- (log revenue / log expense / mark paid)
alter table if exists public.finance_entries
  add column if not exists type text,
  add column if not exists category text,
  add column if not exists amount numeric,
  add column if not exists "date" timestamptz,
  add column if not exists description text,
  add column if not exists linked_event_id uuid,
  add column if not exists linked_event_name text,
  add column if not exists linked_business_id uuid,
  add column if not exists linked_business_name text,
  add column if not exists payment_status text,
  add column if not exists notes text;

-- ── email_templates (EmailTemplate) ──────────────────────────────────────────
-- Writers: pages/Templates.jsx (default seeding, create, edit)
alter table if exists public.email_templates
  add column if not exists title text,
  add column if not exists subject text,
  add column if not exists body text,
  add column if not exists category text,
  add column if not exists merge_fields_used text[],
  add column if not exists created_by_name text,
  add column if not exists use_count integer;

-- ── app_settings (AppSettings) ───────────────────────────────────────────────
-- Writers: pages/Settings.jsx
alter table if exists public.app_settings
  add column if not exists key text,
  add column if not exists value text,
  add column if not exists label text,
  add column if not exists updated_by_name text;

-- ── profiles (User) ──────────────────────────────────────────────────────────
-- Writers: pages/Profile.jsx (profile save, photo, 2FA toggle),
-- components/team/TeamMemberEditDialog.jsx, and the create-user /
-- unlock-account / auth-login-guard Edge Functions.
-- full_name and email are not in base44/entities/User.jsonc (they were Base44
-- built-ins) but base44Client.auth.me() reads full_name and create-user upserts
-- both.
-- failed_login_attempts / account_locked / mfa_enabled repeat
-- 202606260001_invite_security.sql with the same defaults so this file is
-- self-consistent; they are no-ops once that migration has been applied.
alter table if exists public.profiles
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists role text,
  add column if not exists display_name text,
  add column if not exists bio text,
  add column if not exists phone text,
  add column if not exists job_title text,
  add column if not exists profile_photo text,
  add column if not exists linkedin text,
  add column if not exists department text,
  add column if not exists location text,
  add column if not exists skills text[],
  add column if not exists status text,
  add column if not exists subscription_status text,
  add column if not exists paid_through_date timestamptz,
  add column if not exists failed_login_attempts integer not null default 0,
  add column if not exists account_locked boolean not null default false,
  add column if not exists mfa_enabled boolean not null default false;

commit;


-- ═══════════════════════════════════════════════════════════════════════════
-- NEEDS A HUMAN DECISION -- NOT APPLIED ABOVE
-- ═══════════════════════════════════════════════════════════════════════════
--
-- 1. CHECK-constraint conflict: discussions.category = 'archived'
--
--    pages/SyncHub.jsx archives a thread by overwriting its category:
--        base44.entities.Discussion.update(disc.id, { category: 'archived' })
--    and then filters archived threads out with `d.category !== 'archived'`.
--    'archived' is not one of the five values in
--    base44/entities/Discussion.jsonc (general, business, event, idea,
--    announcement), so a CHECK constraint built from that enum rejects every
--    archive action.
--
--    Preferred fix is a separate boolean, which stops archiving from destroying
--    the thread's real category:
--        alter table public.discussions
--          add column if not exists archived boolean not null default false;
--    ...paired with SyncHub.jsx writing { archived: true } and filtering on
--    `!d.archived`.
--
--    If you would rather keep the current single-column design, widen the
--    constraint instead (replace <name> with the real constraint name from
--    \d public.discussions):
--        alter table public.discussions drop constraint if exists <name>;
--        alter table public.discussions add constraint discussions_category_check
--          check (category in ('general','business','event','idea','announcement','archived'));
--
-- 2. Every other enum-like field the app writes matches its reference enum, so
--    no other CHECK needs widening. Verified value sets:
--      businesses.stage        new_lead, contacted, meeting_scheduled,
--                              in_discussion, collaborating, partnered, archived
--      tasks.status            todo, in_progress, done
--      tasks.priority          low, medium, high, urgent
--      ideas.status            new (schema also allows discussing, approved,
--                              in_progress, completed, archived)
--      ideas.category          strategy, partnership, event_concept, marketing,
--                              product, other
--      events.status           planning, confirmed, in_progress, completed, cancelled
--      events.event_type       mixer, workshop, conference, dinner, virtual,
--                              showcase, other
--      interactions.type       call, meeting, email, referral, intro_made,
--                              follow_up, note, event
--      matches.status          suggested, intro_proposed, introduced, dismissed
--                              (schema also allows collaborating)
--      finance_entries.type    revenue, expense
--      finance_entries.category
--                              event_revenue, matchmaking_fee, sponsorship,
--                              consulting, other_revenue, venue_cost, marketing,
--                              operations, software, travel, payroll, other_expense
--      finance_entries.payment_status
--                              paid, pending, overdue
--      email_templates.category
--                              intro, follow_up, event_invite, thank_you,
--                              proposal, custom
--      profiles.role           ceo, admin, user
--      profiles.status         active, inactive, on_leave
--      profiles.subscription_status
--                              active, expired, none
--
-- 3. Column-NAME mismatches: none found. Every field the app writes either
--    matches a column in base44/entities/*.jsonc or is a genuinely new column
--    (discussions.linked_business_name, discussions.linked_event_name,
--    profiles.full_name, profiles.email), so nothing above risks splitting data
--    across a renamed column. In particular events.name and ideas.description
--    are the reference names -- do not "align" them to title/content. The
--    naming is simply inconsistent across tables: events uses name while
--    tasks, ideas, discussions, interactions and email_templates use title;
--    ideas uses description while discussions uses content.
--
-- 4. Empty strings written into uuid and timestamptz columns. These forms send
--    '' for an unset optional value, which Postgres rejects (22P02 / 22007) on
--    any column that is not text. A schema change cannot fix this; the call
--    site has to send null (or omit the key) instead:
--      components/finance/FinanceEntryForm.jsx  linked_event_id, linked_business_id
--      components/sync/NewThreadDialog.jsx      linked_business_id, linked_event_id
--      components/business/LogInteractionForm.jsx  contact_id
--      components/business/BusinessForm.jsx     assigned_to
--      components/team/TeamMemberEditDialog.jsx paid_through_date
--    e.g. in FinanceEntryForm.jsx's submit handler:
--        onSubmit({ ...form, amount: parseFloat(form.amount) || 0,
--                   linked_event_id: form.linked_event_id || null,
--                   linked_business_id: form.linked_business_id || null })
--    If you would rather not touch the forms, declare those five columns as
--    text instead of uuid/timestamptz above. Note this only bites on a column
--    this migration actually creates -- if the live column is already text
--    (which is how the reference schema typed ids: "type": "string"), the
--    ADD COLUMN is a no-op and the form keeps working as it does today.
--
-- 5. created_date / updated_date are a read contract, not a write, so they are
--    not added above. base44Client's list() falls back to
--    .order('created_date', { ascending: false }) for every entity, so every
--    table in the TABLE_MAP needs a created_date column or the list query 400s.
--    updated_date is required on email_templates (list('-updated_date')),
--    businesses (pages/Reports.jsx) and profiles (pages/Team.jsx). Confirm all
--    of these exist; adding them properly needs a default and an updated_date
--    trigger, which is a schema-design decision rather than a gap fix.
--
-- 6. pages/Events.jsx openEdit() does setForm({ ...ev }) and then submits the
--    whole form, so an event update PATCHes id, created_date and updated_date
--    back with their current values. That works today but breaks the moment any
--    of those columns becomes generated or trigger-managed. Worth narrowing the
--    edit payload to the editable fields.
